#pragma once

#define WOW_VERSION '7.25'

#if WOW_VERSION == '7.25'
//System
#define WOW_MEM_IS_CONNECTED 0x016DE318
#define WOW_MEM_GAME_STATE 0x195FE30
#define WOW_MEM_ZONE 0x1961B00
#define WOW_MEM_MOUSEOVER_GUID 0x1960D18

//Player
#define WOW_MEM_PLAYER_BASE 0x18606B8
#define WOW_MEM_PLAYER_UNIT_ORIGIN 0x1560
#define WOW_MEM_PLAYER_X 0x1560
#define WOW_MEM_PLAYER_Y WOW_MEM_PLAYER_UNIT_ORIGIN + 0x4
#define WOW_MEM_PLAYER_Z WOW_MEM_PLAYER_UNIT_ORIGIN + 0x8
#define WOW_MEM_PLAYER_ROTATION WOW_MEM_PLAYER_UNIT_ORIGIN + 0x10
#define WOW_MEM_PLAYER_DESCRIPTORS 0x8120
#define WOW_MEM_PLAYER_HEALTH WOW_MEM_PLAYER_DESCRIPTORS
#define WOW_MEM_PLAYER_MAX_HEALTH WOW_MEM_PLAYER_DESCRIPTORS + 0x20
#define WOW_MEM_PLAYER_TARGET_GUID 0x1961D10

//Object manager
#define WOW_MEM_OBJMGR_BASE 0x16F5650
#define WOW_MEM_OBJMGR_FIRST 0x18
#define WOW_MEM_OBJMGR_NEXT 0x70

//Objects
#define WOW_MEM_OBJ_TYPE 0x20
#define WOW_MEM_OBJ_GUID 0x58
#define WOW_MEM_OBJ_UNIT_ORIGIN 0x4C0
#define WOW_MEM_OBJ_X WOW_MEM_OBJ_UNIT_ORIGIN
#define WOW_MEM_OBJ_Y WOW_MEM_OBJ_UNIT_ORIGIN + 0x4
#define WOW_MEM_OBJ_Z WOW_MEM_OBJ_UNIT_ORIGIN + 0x8
#define WOW_MEM_OBJ_DESCRIPTORS 0x2C08
#define WOW_MEM_OBJ_HEALTH WOW_MEM_OBJ_DESCRIPTORS
#define WOW_MEM_OBJ_MAX_HEALTH WOW_MEM_OBJ_DESCRIPTORS + 0x20
#define WOW_MEM_OBJ_DISPLAY_ID 0x558 //http://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-bots-programs/wow-memory-editing/290318-list-mines-herb-display-ids.html
#endif

#define WOW_OBJECT_TYPE_MINING 0x5
#define WOW_OBJECT_MINERAL_COPPER_ORE 310